#!/bin/bash

# Name: otp-ascii-img, Version: 0.1
# Description: One-time Pad ASCII Graph Image Generator.
# Author: Nikolas Britton
#     E-mail: ytvzwld.mcteezy@rxltw.nzx (caesar, 11)
# Copyright 2021 Nikolas Britton, Apache 2.0 License
# Notes: Imagemagick is a dependency.

test -x /usr/local/bin/convert || {
    echo "Imagemagick's convert utility is a dependency, please install it first.";
    exit 1;
}

#sed -e 's/\(.\)/\1 /g'
convert -density 600 -units pixelsperinch -size 12000x12000 xc:white -font "Monaco" -pointsize 8 -fill black -annotate +15+15 "@otp-ascii-${timestamp}.txt" -trim +repage otp-ascii-${timestamp}.png;
