#!/bin/bash

# Name: otp-ascii-tr, Version: 0.1
# Description: One-time Pad ASCII Graph Transliterator.
# Author: Nikolas Britton
#     E-mail: ytvzwld.mcteezy@rxltw.nzx (caesar, 11)
# Copyright 2021 Nikolas Britton, Apache 2.0 License